#!/usr/bin/env bash

echo "== deploy ec2 instance to interact with MemoryDB"

STACK_NAME="ec2-4-MemoryDB"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy/index.html
aws cloudformation deploy \
  --template-file template.yaml \
  --capabilities CAPABILITY_NAMED_IAM \
  --no-execute-changeset \
  --region us-east-1 \
  --stack-name $STACK_NAME