#!/usr/bin/env bash

# where we'll store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# lets create output folder
mkdir -p $OUTPUT_DIR

# generate a radnom number
# to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=NUM_FILES; i++)); do
  # create a random file name
  FILENAME="$OUTPUT_DIR/file_$i.txt"
  
  # create a random file with some content
  dd if=/dev/urandom of=$FILENAME bs=1024 count=$((RANDOM % 1024 + 1)) 2> /dev/null
  done
