#!/usr/bin/env bash

#yq -o json policy.yaml > policy.json

aws iam create-policy-version \
--policy-arn arn:aws:iam::114743615542:policy/my-fun-policy \
--policy-document "$(yq -o json policy.yaml)" \
--set-as-default